version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ~/Data:/Data:ro
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@fake.com
      PGADMIN_DEFAULT_PASSWORD: 123qwe
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ~/Data:/var/lib/pgadmin/storage/pgadmin_fake.com/Data:ro
volumes:
  local_pgdata:
  pgadmin-data: